Iter5
ChebuRashkaRF/urlshortener pull request #5
Opened 2024-04-12 18:27 UTC by ChebuRashkaRF

2024-04-16 00:02 UTC, avhitrov requested changes
Гонки в данных при работе с сервером, необходимо добавить проверку при сохранении url. В остальном - ок.

2024-04-16 00:02 UTC, avhitrov commented on internal/handler/handler.go
> +var URLMap = make(map[string]string)
Мапа - потоконебезопасная структура, которую при конкурентном использовании на чтение и запись (а http-сервер по умолчанию является конкурентной средой, так как на обработку каждого запроса открывается отдельная горутина) необходимо защищать блокировками. Подробнее: https://t.me/bushigo/24

В данном случае получаем:
```
==================
WARNING: DATA RACE
Read at 0x00c00010aae0 by goroutine 75:
  runtime.mapaccess2_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:108 +0x0
  github.com/ChebuRashkaRF/urlshortener/internal/handler.RedirectHandler()
      C:/work/src/github.com/ChebuRashkaRF/urlshortener/internal/handler/handler.go:42 +0x77
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:73 +0x716
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:73 +0x716
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Previous write at 0x00c00010aae0 by goroutine 7:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  github.com/ChebuRashkaRF/urlshortener/internal/handler.ShortenURLHandler()
      C:/work/src/github.com/ChebuRashkaRF/urlshortener/internal/handler/handler.go:32 +0xef
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:73 +0x716
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 75 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x224
  main.run()
      C:/work/src/github.com/ChebuRashkaRF/urlshortener/cmd/shortener/main.go:31 +0x1a
  main.main()
      C:/work/src/github.com/ChebuRashkaRF/urlshortener/cmd/shortener/main.go:48 +0x31a

Goroutine 7 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x224
  main.run()
      C:/work/src/github.com/ChebuRashkaRF/urlshortener/cmd/shortener/main.go:31 +0x1a
  main.main()
      C:/work/src/github.com/ChebuRashkaRF/urlshortener/cmd/shortener/main.go:48 +0x31a
==================
fatal error: concurrent map read and map write
```
И падение сервера.

2024-04-16 00:02 UTC, avhitrov commented on internal/handler/handler.go
> +	url := string(body)
Неплохо было бы проверить переданные данные на соответствие формату url. Хотя бы с помощью url.Parse...

2024-04-22 15:08 UTC, Perederey approved these changes
Отличная работа, добавил лишь комментарии который надо поправить

2024-04-22 15:08 UTC, Perederey commented on cmd/client/main.go
> +	endpoint := "http://localhost:8080/"
Это бы в конфиг лучше

2024-04-22 15:08 UTC, Perederey commented on cmd/client/main.go
> +	data := url.Values{}
Data - очень общее слово 
Var metrics url.Values

2024-04-22 15:08 UTC, Perederey commented on cmd/client/main.go
> +	fmt.Println("Введите длинный URL")
Лучше бы логгер

2024-04-22 15:08 UTC, Perederey commented on cmd/client/main.go
> +	reader := bufio.NewReader(os.Stdin)
А почему не флаг? Зачем так?

2024-04-22 15:08 UTC, Perederey commented on cmd/client/main.go
> +	request, err := http.NewRequest(http.MethodPost, endpoint, strings.NewReader(data.Encode()))
Один раз запустил и один раз получается можно выполнить запрос?

2024-04-22 15:08 UTC, Perederey commented on cmd/client/main.go
> +		panic(err)
А почему panic?

2024-04-22 15:08 UTC, Perederey commented on cmd/client/main.go
> +	fmt.Println(string(body))
Не понимаю зачем тебе такой клиент? У тебя же http клиент

2024-04-22 15:08 UTC, Perederey commented on cmd/config/config.go
> +		baseURL = "http://localhost:12345"
Base url содержит а себе Port? А зачем тогда порт?

2024-04-22 15:08 UTC, Perederey commented on cmd/shortener/main.go
> +	r.Route("/", func(r chi.Router) {
Тут все в одном и роутер и main, надо разграничить

2024-04-22 15:08 UTC, Perederey commented on cmd/shortener/main.go
> +	serverAddress := flag.String("a", ":8080", "server address")
Лучше flag.StringVar

2024-04-22 15:08 UTC, Perederey commented on cmd/shortener/main_test.go
> +	assert.Contains(t, body, config.Cnf.BaseURL)
Assert.JSONEq() - так будет лучше

2024-04-22 15:08 UTC, Perederey commented on cmd/storage/storage.go
> +	URLMap   map[string]string
Проще сразу map из пакета sync использовать

2024-05-11 10:54 UTC, merged